const keys = {
    SESSION_USER_REAL_NAME: 'SESSION_USER_REAL_NAME',
    SESSION_USER_ID: 'SESSION_USER_ID',
    SESSION_ADMIN_TOKEN: 'SESSION_ADMIN_TOKEN',
    SESSION_REGISTER_FLAG: 'SESSION_REGISTER_FLAG',
    // localStorage
    LOCAL_USER_NICK_NAME: 'LOCAL_USER_NICK_NAME',
    LOCAL_USER_PASSWORD: 'LOCAL_USER_PASSWORD'
};

export default keys;
